---
- name: Patching Check a Change before starting
  hosts: all
  gather_facts: false
  tasks:
    - name: Include vars
      ansible.builtin.include_vars: ../vars/snow.yml

    - name: Check Change State
      servicenow.itsm.change_request_info:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_user }}"
          password: "{{ snow_pass }}"
        number: "{{ snow_chg_no }}"
      register: chg_details

    - name: Print Change Record details
      ansible.builtin.debug:
        var: chg_details.records

    - name: Display a nice message
      ansible.builtin.debug:
        msg: "Change State - {{ chg_details.records.0.state }}"
      when: "chg_details.records | length > 0"

    - name: Error out if no records returned
      ansible.builtin.fail:
        msg: "{{ snow_chg_no }} has returned no records from SNOW, Please Check and re-enter"
      when: "chg_details.records | length == 0"

    - name: Check if Change Record is in scheduled state
      ansible.builtin.fail:
        msg: "{{ snow_chg_no }} is currently reporting as {{ chg_details.records.0.state }}, A Change must be in scheduled or implement before proceeding"
      when: (chg_details.records.0.state != 'scheduled') and (chg_details.records.0.state != 'implement')

    - name: Pull CI Name from Change sys id
      servicenow.itsm.configuration_item_info:
        instance:
          host: "{{ snow_host }}"
          username: "{{ snow_user }}"
          password: "{{ snow_pass }}"
        sys_id: "{{ chg_details.records.0.cmdb_ci }}"
      register: cmdb_result

    - name: Display a nice message
      ansible.builtin.debug:
        var: cmdb_result.records.0.name

    - name: Check if Change is for the host being run against
      ansible.builtin.fail:
        msg: "The host requested {{ inventory_hostname }} does not match the change record in SNOW {{ cmdb_result.records.0.name }}. Please ensure this is the correct change and re-try"
      when: inventory_hostname != cmdb_result.records.0.name
